name:  Clickables
author:  davidwalsh
current:  1.0
category:  Interface
tags:  [events,links]
docs:  http://davidwalsh.name/dwclickable-entire-block-clickable-mootools
demo:  http://davidwalsh.name/dwclickable-entire-block-clickable-mootools